name: demo3
description: Gophr demo app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  dio: ^4.0.6
  go_router: ^3.1.0
  json_serializable: ^6.2.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.10
  freezed: ^2.0.3
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true